INSERT INTO `characters` (`id`, `name`, `img`, `sex`, `weight`, `skill`, `description`, `typeId`) VALUES
(1, 'Peter Pan', 'peter_pan.jpg', 'm', 45, 'vliegen', 'Peter Pan is een personage verzonnen door de Schotse schrijver J.M. Barrie (1860-1937). Hij werd voor het eerst opgevoerd in de roman The Little White Bird uit 1902, vier jaar later herschreven tot het kinderboek Peter Pan in Kensington Gardens.\r\n\r\nPeter Pan is echter vooral bekend van het avontuur waarin hij de Londense kinderen Wendy, Michiel en Jan Schat meeneemt naar Nooitgedachtland en het opneemt tegen de piraat kapitein Haak. Dit verhaal werd in 1904 voor het eerst opgevoerd als toneelstuk onder de titel Peter Pan, or The Boy Who Would Not Grow Up. In 1911 volgde de roman Peter and Wendy. De bekendste uitvoering is de Disneytekenfilm Peter Pan uit 1953.\r\n\r\nDe figuur Peter Pan komt in diverse boeken en films voor, waaronder Hook (1991), Return to Never Land (2002) en Finding Neverland (2004).', 2),
(2, 'Cruella de Vil', 'Cruella_de_Vil.gif', 'f', 65, 'Omkopen', 'Cruella de Vil is een fictief personage dat verscheen in het boek 101 Dalmatiërs van Dodie Smith uit 1956. Daarna verscheen ze in de Disney-animatiefilm 101 Dalmatiërs, het vervolg daarop 101 Dalmatiërs II: Het avontuur van Vlek in Londen (2003) en de \'live action\' films 101 Dalmatiërs (1996) en 102 Dalmatiërs (2000) met Glenn Close in de rol van Cruella. In al haar verschijningen probeert Cruella 99 dalmatiërpuppy\'s te ontvoeren om van hun vacht bontjassen te maken.', NULL),
(3, 'Robin Hood', 'robin_hood.png', 'm', 80, 'Boogschieten', 'Robin Hood is een Engelse volksheld uit een reeks oude balladen en legenden. Volgens de verhalen zou hij stelen van de rijken en zijn buit vervolgens verdelen onder de armen,[1] samen met een groep vrijbuiters, genaamd de Vrolijke Volgelingen (\'Merry Men\').[2] Hij woonde in Sherwood Forest (Nottinghamshire), waar hij tegen de gezagsdragers gestreden zou hebben. Deze middeleeuwse held is wereldwijd bekend geworden door vele verhalen en verfilmingen ervan.', NULL),
(4, 'Pinokkio', 'pinokkio.jpg', 'm', 14, 'Waarheid spreken', 'Pinokkio (van het Italiaans Pinocchio, \"stukje pijnboom\") is een personage en de hoofdpersoon uit het kinderboek De avonturen van Pinokkio (Le avventure di Pinocchio) uit 1883, geschreven door de Italiaan Carlo Collodi. Pinokkio werd door een houtbewerker genaamd Geppetto gemaakt, in een klein Italiaans dorp. Hij creëerde een houten pop, maar droomde ervan dat het een echte jongen was. Zijn personage werd later ook gebruikt om leugens en vele fantasieverhalen rond te vertellen. Het verhaal rond Pinokkio is al in vele varianten verschenen en ook bewerkt voor moderne media. Pinokkio wordt een icoon genoemd in de moderne media en is een van de vele bekende personages uit de kinderliteratuurgeschiedenis.\r\n\r\nPinokkio staat bekend om zijn korte neus die langer wordt als hij nerveus wordt, zeker als hij liegt.', NULL),
(5, 'Goofy', 'goofy.gif', 'm', 30, 'Onhandigheid', 'Goofy is een personage uit de tekenfilms en stripverhalen van Disney. Hij werd in 1932 bedacht door Art Babbitt en de eerste concepten werden uitgewerkt door Frank Webb. Goofy is de beste vriend van Mickey Mouse. Zijn uiterlijk is gebaseerd op de Australische dingo.[1]\r\n\r\nIn de tekenfilmpjes van Walt Disney werd de stem van Goofy jarenlang gedaan door de stemmenkunstenaar Pinto Colvig.', 1),
(6, 'Ariel', 'ariel.png', 'f', 56, 'Zwemmen', 'Ariël is een mooie, jonge zeemeermin en een van de zeven dochters van koning Triton en koningin Athena. Haar moeder Athena is overleden vóór de eerste film. Haar zussen heten Aquata, Andrina, Arista, Attina, Adella en Alana. Ze woont in Atlantica, het zeekoninkrijk van haar ouders. Ariël is avontuurlijk en nieuwsgierig en heeft een obsessie voor mensen en hun spullen die zij in het geheim verzamelt in een grot. Haar vader kan dit absoluut niet waarderen omdat hij mensen als gevaarlijk ziet. Hij wijst daarom zijn hofmuzikant, Sebastiaan de krab, aan om op haar te letten. Ariëls beste vriend is de vis Botje. Ze heeft lang rood haar, een lichte huidskleur, grote blauwe ogen, een paarse schelpvormige bh en een groene zeemeerminnenstaart. Ariël wordt soms prinses genoemd, of \"kleine zeemeermin\".', NULL),
(7, 'Garfield', 'garfield.jpg', 'm', 6, 'Eten', 'Garfield is een luie, dikke, zelfingenomen, oranje kat die houdt van eten, slapen, het eten van zijn baasje Jon stelen en de hond Odie te pesten. Hij haat maandagen omdat hij op die dag altijd pech heeft (vaak in de vorm van een taart in zijn gezicht). Hij beschouwt zichzelf als intelligenter dan mensen en honden.\r\n\r\nGarfield geeft graag \'s avonds shows weg op een houten schutting vlak bij zijn huis. Zijn publiek is echter nooit tevreden, en gooit vaak met schoenen, fruit, groente of andere dingen die binnen handbereik liggen voor hem. Garfield is te lui om op muizen te jagen, tot irritatie van zijn baas Jon. Wel jaagt Garfield op spinnen, die hij meestal plat slaat met een krant. Andere dingen waar Garfield zich aan ergert zijn diëten en rozijnen.', NULL),
(8, 'Grote Smurf', 'Grote_Smurf.jpg', 'm', 1, 'Wijsheid', 'Grote Smurf is te herkennen aan zijn rode muts, rode broek en witte baard. De meeste andere Smurfen zijn in het wit gekleed. Hoewel zijn leeftijd niet exact bekend is, wordt in een aantal stripverhalen van de Smurfen een aantal levensjaren genoemd. De meest voorkomende is 542 jaar.\r\n\r\nDe Grote Smurf heeft veel gezag en ervaring en neemt bijna altijd in zijn eentje de belangrijke beslissingen. Hij heeft een laboratorium (met op de deur het opschrift \"Verboden te smurfen\") in het Smurfendorp met daarin allerlei toverboeken, zodat hij kan wedijveren met tovenaar Gargamel. De Grote Smurf kan zijn toverkracht ook gebruiken om de Smurfen een wijze les te leren, als zij strijd met elkaar hebben of als de eenheid in het Smurfendorp in gevaar is.', NULL),
(9, 'Tom', 'tom.png', 'm', 7, 'Doorzettingsvermogen', 'Tom is een blauw-grijze huiskat (hoogstwaarschijnlijk een Blauwe Rus), die een luizenleventje heeft, terwijl Jerry een kleine, bruine muis is die in hetzelfde huis woont. Tom is agressief, egoïstisch en pesterig. Jerry kan ook gemeen uit de hoek komen, maar is doorgaans veel intelligenter dan Tom. Meestal wint Jerry dan ook van Tom. Toch heerst er tussen beiden ook een vriendschappelijke band. In sommige filmpjes redden ze elkaar in geval van nood, gevaar of een wederzijds probleem.', NULL),
(10, 'Winnie de Pooh', 'winnie_de_pooh.jpg', 'm', 5, 'Snoepen', 'Winnie de Poeh (Engels: Winnie-the-Pooh) is een personage uit een verhalenreeks van A.A. Milne. Zijn naam is eigenlijk Beer Edward, maar hij wordt zelden zo genoemd. Poeh-beer, zoals hij ook wel wordt genoemd, is dol op honing en heeft naar eigen zeggen maar een heel klein beetje verstand.\r\n\r\nWinnie de Poeh is eigenlijk de knuffelbeer van Christopher, maar kan in de verhalen praten, net als de andere speeldieren en woont in het Honderd Bunderbos, geënt op een echt bosje in de buurt van het huis van de schrijver. Poeh, Christopher en Knorretje beleven in de verhalen van Milne eenvoudige avonturen die bijvoorbeeld als motief hebben dat Poeh van honing houdt, of dat er een nieuw dier in het bos is komen wonen, of dat de dieren op ontdekkingstocht gaan. Winnie de Poeh heeft veel vrienden: Christopher, Knorretje, Teigetje, Kanga, Roe, Iejoor, Konijn en Uil.', NULL);

INSERT INTO `types` (`id`, `name`) VALUES
(1, 'Dier'),
(2, 'Mens'),
(3, 'Fictief');

COMMIT;